import json

def type_to_offset(given_type):
  if given_type == "bool":
    # OpenGOAL "bools" are usually "symbols" but symbols are 4 bytes.  TOO BIG instead we use uint8's set to 0 or 1
    return 1
  elif given_type == "uint8":
    return 1
  elif given_type == "uint16":
    return 2
  elif given_type == "uint32":
    return 4
  elif given_type.startswith("uint8["):
    return 1 * int(given_type.split("[")[1].split("]")[0])

def type_to_typename(given_type):
  # Convert to C# type names
  if given_type == "bool":
    return "byte"
  elif given_type == "uint8":
    return "byte"
  elif given_type == "uint16":
    return "ushort"
  elif given_type == "uint32":
    return "uint"

def generate_option_string(listVarName, label, offset, type, size, name):
  return "  AddOption(vars.{}, \"{}\", {}, typeof({}), {}, false, \"{}\", false);\n".format(listVarName, label, offset, type, size, name)

def generate_options(input_file, output_file):
  # Settings To Emit
  preset_settings = []
  manual_settings = []
  # Read in json file
  with open(input_file, 'r') as f:
    options = json.load(f)
    curr_offset = 0
    for option in options["structFields"]:
      if "hidden" not in option or option["hidden"] is not True:
        # Add to manual settings
        option_name = option["label"]
        if "name" in option:
          option_name = option["name"]
        manual_settings.append(generate_option_string("manualOptions", option["label"], curr_offset, type_to_typename(option["type"]), type_to_offset(option["type"]), option_name))
      curr_offset = curr_offset + type_to_offset(option["type"])
  # Write to output file
  new_lines = []
  with open(output_file, 'r') as f:
    lines = f.readlines()
    ignore_lines = False
    for line in lines:
      if "// __AUTOGENERATED__ START" in line:
        ignore_lines = True
        new_lines.append(line)
        # Add our settings!
        new_lines.append("  vars.manualOptions = new List<Dictionary<String, dynamic>>();\n")
        for setting in manual_settings:
          new_lines.append(setting)
        new_lines.append("  settings.Add(\"manual_options\", true, \"Manual Options\");\n")
        new_lines.append("  AddToSettings(vars.manualOptions, \"manual_options\");\n")
        continue
      elif "// __AUTOGENERATED__ END" in line:
        ignore_lines = False
        new_lines.append(line)
        continue
      if not ignore_lines:
        new_lines.append(line)
  with open(output_file, 'w') as f:
    f.writelines(new_lines)


generate_options("./jak2/options.json", "./jak2/opengoal-jak2-autosplitter.asl")
